# Generated by Django 2.2.5 on 2020-11-29 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20201128_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedperiod',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.Reservation'),
        ),
    ]
